### ISSUE TITLE
runNanoSeq.py var and post by NanoSeq 3.5.4 fails for some of samples that NanoSeq 3.5.1 run successfully.

### ISSUE THREAD

**Issue by monagai** [cancerit/NanoSeq#85]
I'm trying to use NanoSeq for rat and mouse samples.
runNanoSeq.py var and post by NanoSeq 3.5.4 fails for samples that NanoSeq 3.5.1 run successfully.
It is only a report because I have not clarified the condition of NanoSeq 3.5.4 error.

1. runNanoSeq.py var fails with one of  fragment in 60 threads. (2 samples)

2. runNanoSeq.py post fails (several samples)
```
...
Executing: variantcaller.R ./tmpNanoSeq/post/ > ./tmpNanoSeq/post/summary.txt


Executing: nanoseq_results_plotter.R ./tmpNanoSeq/post ./tmpNanoSeq/post/results 

Traceback (most recent call last):
  File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 1156, in <module>
    runCommand(cmd)
  File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 430, in runCommand
    raise ValueError(error)
ValueError: Error in base::table(...) : nothing to tabulate
Calls: table ... standardGeneric -> eval -> eval -> eval -> table -> <Anonymous>
Execution halted
```

**Comment by fa8sanger** [comment]
It’s difficult to know without having a look to the data.

About the first error, is there any error message? Have you tried rerunning the failed job? Sometimes we get failed jobs because of errors in our computer farm rather than errors of the pipeline.

About the second error, my advice would be to open an R console and run nanoseq_results_plotter.R  interactively, copying line by line and inspecting the results.

Let me know when you find more clues
Thank you

On 23 Jan 2024, at 03:48, Momoko NAGAI ***@***.***> wrote:



I'm trying to use NanoSeq for rat and mouse samples.
runNanoSeq.py var and post by NanoSeq 3.5.4 fails for samples that NanoSeq 3.5.1 run successfully.
It is only a report because I have not clarified the condition of NanoSeq 3.5.4 error.

  1.  runNanoSeq.py var fails with one of fragment in 60 threads. (2 samples)

  2.  runNanoSeq.py post fails (several samples)

...
Executing: variantcaller.R ./tmpNanoSeq/post/ > ./tmpNanoSeq/post/summary.txt


Executing: nanoseq_results_plotter.R ./tmpNanoSeq/post ./tmpNanoSeq/post/results

Traceback (most recent call last):
  File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 1156, in <module>
    runCommand(cmd)
  File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 430, in runCommand
    raise ValueError(error)
ValueError: Error in base::table(...) : nothing to tabulate
Calls: table ... standardGeneric -> eval -> eval -> eval -> table -> <Anonymous>
Execution halted


—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_85&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_EGgzhAingqGS0jzkjN9ZX96VaNtB_RqX53Q8W0C6AnzTovnh35lGQ5MdsR1Aaff&s=SdenrDGJRC82ucvE_cVqpALc-_HCnuh_D9_Bq4YuHus&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KPYGPN7N5A4XCAI3TYP4XIFAVCNFSM6AAAAABCGITJBCVHI2DSMVQWIX3LMV43ASLTON2WKOZSGA4TKMJYGUZTMMA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_EGgzhAingqGS0jzkjN9ZX96VaNtB_RqX53Q8W0C6AnzTovnh35lGQ5MdsR1Aaff&s=NV1lLK3FZxQBw6RaF_ym6cefXbIJ54rUsVBfR-q4oks&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by monagai** [comment]
I really thank you for your quick comment.

> 1. runNanoSeq.py var fails with part of fragments in 60 threads. (2 samples)

Sorry, this happened for only 1 samples.
There is no error log from `var` command about it. `post` command reports error.

I undestand that these error depend on samples.
This issue is a report.
NanoSeq 3.5.4 seems a little bit unstable compared to 3.5.1...
